version: '3.9'
services:
  pgdb:
    image: 'postgres:14'
    volumes:
      - pg:/var/lib/postgresql/data
    environment:
      POSTGRES_DATABASE: 'falcon_manager'
      POSTGRES_USER: 'testuser'
      POSTGRES_PASSWORD: 'testpass'
      POSTGRES_ROOT_PASSWORD: 'root'
    ports:
      - '5432:5432'
volumes:
  pg:
    name: falcon_manager

